version: '3'
services:
  app:
    image: covidhelphub-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    env_file:
      - ${ENV_FILE}
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
