FROM node:14-alpine

# Create api directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn.lock ./
# Copying Prisma schema for when we need it later to genrate clients/migrate/deploy
COPY prisma ./prisma/

RUN yarn install
# Generating a prisma client (could be done using a CMD script in future for CI/CD)
RUN npx prisma generate
# Bundle app source
EXPOSE 4000

# Run app
# command is inside docker-compose