FROM node:14-alpine

# Create api directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
EXPOSE 4000

# Run app
# command is inside docker-compose