version: '3'
services:
  app_common:
    image: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    env_file:
      - ${ENV_FILE}
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules